import Head from 'next/head'
import Navbar from './components/navbar'
import Banner from './components/banner'
import Activities from './components/activities'
import FeaturedProject from './components/featuredProject'
import Footer from './components/footer'


export default function Home() {
  return (
    <div>
      <Head>
        <title className='res'>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Navbar />

      <Banner/>

      <Activities/>

      <FeaturedProject />
      <Footer />
    </div>
  )
}